default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USER", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  port: <%= ENV.fetch("PG_PORT", 5432) %>

development:
  <<: *default
  database: expo_mvp_development

test:
  <<: *default
  database: expo_mvp_test

production:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE", "expo_mvp_production") %>
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  host: <%= ENV.fetch("PG_HOST") %>
  port: <%= ENV.fetch("PG_PORT", 5432) %>
